name: .NET Selenium Tests for Saucedemo

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        category: [PositiveTests, NegativeTests]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test Tests/WEB/WebTest.cs --filter "(TestCategory=PositiveTests|TestCategory=NegativeTests)" --logger "trx;LogFileName=combined-results$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults

      - name: Retry tests on failure
        run: |
          dotnet test Tests/WEB/WebTest.cs --logger "trx;LogFileName=test-results-$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults || dotnet test Tests/WEB/WebTest.cs --logger "trx;LogFileName=test-results-$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.browser }}-${{ matrix.category }}-results
          path: TestResults/

      - name: List test result files
        run: ls -la TestResults/

      - name: Capture and upload screenshot on failure
        if: failure()
        run: |
          echo "Test failed. Uploading screenshot..."
          if [ -f "screenshot.png" ]; then
            mkdir -p artifacts
            mv screenshot.png artifacts/
          else
            echo "No screenshot found."
          fi
        continue-on-error: true

      - name: Upload screenshot if test fails
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: artifacts/screenshot.png

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use action to generate test report
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Tests/WEB/WebTest.cs
          report_name: '.NET Selenium test - Saucedemo'
