name: .NET Test with Allure Report

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore

      - name: Run tests and generate Allure results
        run: dotnet test --logger "nunit;LogFileName=TestResults.xml"

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.tgz
          tar -zxvf allure-2.14.0.tgz
          sudo mv allure-2.14.0 /usr/local/allure

      - name: Serve Allure report
        run: allure serve TestResults/allure-results

