name: Run Tests in Parallel with Multiple .NET Versions

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        browser: [ 'chrome' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      # Set up .NET SDK versions
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      # Install dependencies
      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool install --global Selenium.WebDriver
          dotnet tool install --global Selenium.WebDriver.ChromeDriver
      
      # Set up Selenium and run tests in parallel
      - name: Run tests in parallel on Chrome
        run: |
          # Start Selenium Grid or WebDriver on different Chrome instances (adjust as needed)
          docker-compose up -d  # Start the required services (like Selenium Grid)

          # Run tests on the parallel browsers
          dotnet test --filter Browser=${{ matrix.browser }} --logger "trx;LogFileName=TestResults-${{ matrix.dotnet-version }}.trx" --results-directory "TestResults-${{ matrix.dotnet-version }}"

      # Take screenshots on test failure
      - name: Take screenshot if test fails
        if: ${{ failure() }}
        run: |
          mkdir -p screenshots
          cp -r $(pwd)/TestResults-${{ matrix.dotnet-version }}/*.png screenshots/

      # Upload test results
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}
      
      # Upload screenshots on failure
      - name: Upload screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
