name: Selenium test - Saucedemo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  execute-selenium-ui-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        shard: [1, 2, 3]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --logger "trx;LogFileName=test-results-$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults

    - name: Retry tests on failure
      run: |
        dotnet test --logger "trx;LogFileName=test-results-$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults || dotnet test --logger "trx;LogFileName=test-results-$(date +%Y%m%d%H%M%S).trx" --results-directory TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/

    - name: List test result files
      run: ls -la TestResults/

    - name: Capture and upload screenshots on failure
      if: failure()
      run: |
        echo "Test failed. Uploading screenshots..."
        mkdir -p TestResults/screenshots
        cp TestResults/screenshots/*.png TestResults/screenshots/ || true
      continue-on-error: true

    - name: Upload screenshots if test fails
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: TestResults/screenshots/*
        if-no-files-found: warn
        include-hidden-files: false
