name: Selenium test - Saucedemo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        shard: [1, 2, 3]
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup Selenium WebDriver
      run: |
        # Fetch the latest stable Chrome version
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
        VERSION=$(echo $CHROME_VERSION | sed 's/\.[0-9]*$//') # Get the major version
        echo "Installing ChromeDriver for version: $VERSION"
    
        # Download and install the corresponding ChromeDriver
        wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$VERSION
        DRIVER_VERSION=$(cat LATEST_RELEASE_$VERSION)
        wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
    
        # Unzip and move to /usr/local/bin
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin
        chromedriver --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with NUnit
      run: |
        dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory TestResults --filter "TestCategory=Functional"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/test-results.trx

    # Capture and upload screenshot if test fails
 
