name: Selenium test - Saucedemo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        shard: [1, 2, 3]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build Saucedemo --no-restore
    - name: Test
      run: dotnet test Saucedemo --logger:trx --results-directory TestResults
 # 5. Upload test results
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/
